version: "3.8"

services:
  java-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: java-dev-container
    ports:
      - "8080:8080" # Mapeia a porta 8080 do container para a porta 8080 do host
    volumes:
      - .:/workspace # Mapeia o diretório atual para /workspace no container
    tty: true # Mantém o terminal aberto
